<a href="https://colab.research.google.com/github/bagcakaya/Assignment-1/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [2]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

#### 4. Generate an array 4x4 ones assign data type int

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

#### 5. Make all the values of the array above 7

In [75]:
np.array(7)

array(7)

#### 6. Create same array above with full method

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [76]:
np.arange(2,18,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [81]:
np.arange(0,25, dtype="int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [17]:
np.linspace(0,25,25, dtype="int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

#### 10. Create 5 random number with numpy

In [18]:
np.random.rand(5)

array([0.48073215, 0.84695262, 0.58865469, 0.8121665 , 0.94088681])

#### 11. Create random normal distributed 5x5 array

In [19]:
np.random.randn(5,5)

array([[ 0.75169453,  0.45786042, -1.27506834,  0.5644421 ,  0.47598214],
       [ 0.33728768, -1.9056237 , -1.37228152, -1.38769934, -1.84459449],
       [ 0.56806108, -0.31220191, -2.02143032, -0.11108292, -0.86176272],
       [-0.19940096, -0.1865421 ,  1.31478949,  1.04184398,  1.45459503],
       [ 0.01742086,  0.74332127,  1.16387245,  1.06698695, -3.31152599]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [20]:
np.random.randint(20,50, size=(3,4))

array([[35, 36, 21, 37],
       [39, 33, 47, 33],
       [48, 41, 28, 27]])

#### 13. Reshape the array below with shape 6x8

In [21]:
ranarr = np.random.randint(0, 60, 48)

In [22]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([49, 47, 38, 56, 10, 37, 43,  8, 50, 31,  7, 16, 21,  4, 27, 49,  5,
       41,  3, 50, 27, 39, 18, 36, 54, 20, 36, 46, 23, 51, 19, 13, 11,  0,
       50, 24, 47, 48, 36, 55, 12, 34, 31, 38,  8, 37, 44,  1])

In [23]:
ranarr.reshape(6,8)

array([[49, 47, 38, 56, 10, 37, 43,  8],
       [50, 31,  7, 16, 21,  4, 27, 49],
       [ 5, 41,  3, 50, 27, 39, 18, 36],
       [54, 20, 36, 46, 23, 51, 19, 13],
       [11,  0, 50, 24, 47, 48, 36, 55],
       [12, 34, 31, 38,  8, 37, 44,  1]])

In [24]:
#reshape with -1
ranarr.reshape(-1,6)

array([[49, 47, 38, 56, 10, 37],
       [43,  8, 50, 31,  7, 16],
       [21,  4, 27, 49,  5, 41],
       [ 3, 50, 27, 39, 18, 36],
       [54, 20, 36, 46, 23, 51],
       [19, 13, 11,  0, 50, 24],
       [47, 48, 36, 55, 12, 34],
       [31, 38,  8, 37, 44,  1]])

## Numpy Indexing and Selection


In [25]:
#Create array below
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [26]:
arr1[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [27]:
arr1[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [28]:
arr1[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [29]:
arr1[0:,2]=77
arr1

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [30]:
arr1[[1,3],[0,2]]

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [31]:
arr1[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [32]:
arr1[arr1<10]

array([1, 2, 4, 5, 6, 8, 9])

In [34]:
arr1[arr1>12]

array([77, 77, 77, 13, 14, 77, 16])

In [35]:
arr1[arr1<10] + arr1[arr1>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [36]:
(arr1[arr1<10] + arr1[arr1>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [37]:
#print array here
arr1

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [38]:
arr1[0:,2]=[3,7,11,15]
arr1 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
arr1[:,1].sum()

32

#### 23. Get the median,mean and std of 3rd column from array above

In [42]:
#median
np.median(arr1[2])

10.5

In [43]:
#mean
np.mean(arr1[2])

10.5

In [44]:
#std
np.std(arr1[2])

1.118033988749895

# Pandas Section

In [45]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [47]:
sal1 = pd.read_csv("Salaries.csv")
sal1

Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[148654 rows x 13 columns]

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [48]:
sal1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [49]:
sal1.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [51]:
sal1.Year.value_counts(dropna=False)

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [52]:
#max
sal1.TotalPay.max()

567595.43

In [53]:
#avg
sal1.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [55]:
sal1[sal1.TotalPay>TotalPay.mean()]

NameError: ignored

**How much does ALBERT PARDINI make (including benefits)?**

In [57]:
sal1[sal1.EmployeeName=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [58]:
sal1[sal1.TotalPayBenefits==sal1.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [60]:
sal1.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [61]:
sal1.JobTitle.value_counts.tail(3)

AttributeError: ignored

**How many people earned more than avg in 2012**

In [62]:
len(sal1[(sal1.TotalPayBenefits>sal1.TotalPayBenefits.mean()) & (sal1.Year==2012)])

20366

**How many people have the word Manager in their job title?**

In [64]:
#use apply function here
sal1[sal1.JobTitle.apply(lambda x : True if "manager" in x.lower else False)]

TypeError: ignored

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [65]:
sal2 = sal1.iloc[:,[0,1,2,7,8]]
sal2

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [66]:
sal2 = sal2.loc[:,"EmployeeName" :"TotalPayBenefits"]
sal2

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [70]:
sal1[(sal1.TotalPayBenefits > sal1.TotalPayBenefits.min() or (sal1.TotalPayBenefits < sal1.TotalPayBenefits.mean()))]["EmployeeName"]

ValueError: ignored